name: Train Drug Classification Model  
run-name: Training task triggered by ${{ github.actor }}. 🚀
on: 
  pull_request_target:
    branches:
    - main 

jobs: 
  train-model: 
    name: Train Model 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v4

      - name: Setup Ruff 
        uses: astral-sh/ruff-action@v3

        # To pin python version 
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ruff Lint Check  
        run:  |
          ruff check .

      - name: Ruff Format Check  
        run:  |
          ruff format --check . 

      - name: Install dependencies 
        run: 	pip3 install -U -r requirements.txt

      - name: Train model
        run: 	python3 train.py 

      - name: Comment Model metrics on PR
        uses: actions/github-script@v7
        with:
          script: | 
            const fs = require('fs');
            const metrics = JSON.parse(fs.readFileSync('./results/metrics.json', 'utf8'));
            const body = `### 📊 Model Metrics
            - **Accuracy**: ${metrics.accuracy_score}
            - **F1 Score**: ${metrics.F1_score}
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });


        




